name: Build Release

on:
  push:
    tags:
      - "*"

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node@16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout plugin
        uses: actions/checkout@v3

      - name: Build plugin
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: build
          prefix: ${{ github.event.repository.name }}
          targets: linux/amd64,linux/arm64,darwin/arm64,darwin/amd64
          v: true
          buildmode: plugin

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
